// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA44t5IP4I_y_Cfs25VITjNOxU5F-oJt2M',
    appId: '1:303716693653:web:78bb5c51635624e7888d9c',
    messagingSenderId: '303716693653',
    projectId: 'flutter-demo-a84d5',
    authDomain: 'flutter-demo-a84d5.firebaseapp.com',
    storageBucket: 'flutter-demo-a84d5.firebasestorage.app',
    measurementId: 'G-S46FP4XRYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5iEg-Mzkgw5B1svp02wEG6In4NSmG5sk',
    appId: '1:303716693653:android:8ec3f7915b259032888d9c',
    messagingSenderId: '303716693653',
    projectId: 'flutter-demo-a84d5',
    storageBucket: 'flutter-demo-a84d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtgWGwsKTq6KpRyeeyOOcAFHAecQb6c18',
    appId: '1:303716693653:ios:7753ba56699e868e888d9c',
    messagingSenderId: '303716693653',
    projectId: 'flutter-demo-a84d5',
    storageBucket: 'flutter-demo-a84d5.firebasestorage.app',
    iosBundleId: 'com.example.lesson02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtgWGwsKTq6KpRyeeyOOcAFHAecQb6c18',
    appId: '1:303716693653:ios:fbb96b3a4571b417888d9c',
    messagingSenderId: '303716693653',
    projectId: 'flutter-demo-a84d5',
    storageBucket: 'flutter-demo-a84d5.firebasestorage.app',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA44t5IP4I_y_Cfs25VITjNOxU5F-oJt2M',
    appId: '1:303716693653:web:054d1cc25266d25b888d9c',
    messagingSenderId: '303716693653',
    projectId: 'flutter-demo-a84d5',
    authDomain: 'flutter-demo-a84d5.firebaseapp.com',
    storageBucket: 'flutter-demo-a84d5.firebasestorage.app',
    measurementId: 'G-KCC2TWSBMC',
  );
}
